'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/contexts/AuthContext';
import { useNotification } from '@/contexts/NotificationContext';
import Button from '@/components/ui/Button';
import Card from '@/components/ui/Card';
import Input from '@/components/ui/Input';
import CategoryChecklist, { CategoryItem } from '@/components/ui/CategoryChecklist';
import AllowancePrompt, { AllowanceType } from '@/components/ui/AllowancePrompt';
import type { RoomDetail } from '@/components/ui/DynamicRoomBuilder';
import RoomChecklist, { RoomSelection, CustomRoom } from '@/components/ui/RoomChecklist';
import RoomSelectionOptions from '@/components/ui/RoomSelectionOptions';
import CabinetryBuilder, { CabinetryDetail } from '@/components/ui/CabinetryBuilder';
import RoomCountSelector, { RoomCounts } from '@/components/ui/RoomCountSelector';
import AutoGeneratedRoomList, { GeneratedRoom } from '@/components/ui/AutoGeneratedRoomList';
import CredentialsModal from '@/components/ui/CredentialsModal';
import { apiClient } from '@/lib/api/client';
import { countRoomsFromDetails } from '@/lib/projects/roomCounts';
import defaultTemplates from '@/lib/templates/defaultProjectTemplates.json';
import { useSetupDesign } from '@/hooks/useSetupDesign';
import { DEFAULT_STANDARD_ROOMS } from '@/lib/setupDesign/defaults';
import { getDefaultBudgetCategories, type BudgetCategory } from '@/lib/constants/budget-categories';

interface CategoryAllowance {
  categoryId: string;
  amount: number;
  type: AllowanceType;
}

const DEFAULT_CATEGORIES: CategoryItem[] = [
  { id: 'flooring', name: 'Flooring', required: true, completedCount: 0, totalCount: 0 },
  { id: 'lighting', name: 'Lighting', required: true, completedCount: 0, totalCount: 0 },
  { id: 'plumbing', name: 'Plumbing', required: true, completedCount: 0, totalCount: 0 },
  { id: 'tile', name: 'Tile', required: true, completedCount: 0, totalCount: 0 },
  { id: 'countertops', name: 'Countertops', required: true, completedCount: 0, totalCount: 0 },
  { id: 'hardware', name: 'Hardware', required: true, completedCount: 0, totalCount: 0 },
  { id: 'exterior', name: 'Exterior', required: false, completedCount: 0, totalCount: 0 },
  { id: 'appliances', name: 'Appliances', required: false, completedCount: 0, totalCount: 0 },
  { id: 'cabinetry', name: 'Cabinetry', required: false, completedCount: 0, totalCount: 0 },
];

const buildRoomSelections = (rooms = DEFAULT_STANDARD_ROOMS): RoomSelection[] =>
  rooms.map((room) => ({
    type: room.type,
    displayName: room.displayName,
    quantity: 0,
    selected: false,
  }));

type Step = 'basic' | 'roomCounts' | 'roomNames' | 'roomSelections' | 'exterior' | 'cabinetry' | 'categories' | 'budgets' | 'template';

function buildRoomName(room: RoomSelection, index: number) {
  if (room.type === 'bedroom') return index === 0 ? 'Primary Bedroom' : `Bedroom ${index + 1}`;
  if (room.type === 'bathroom') return index === 0 ? 'Primary Bathroom' : `Bathroom ${index + 1}`;
  return room.quantity > 1 ? `${room.displayName} ${index + 1}` : room.displayName;
}

function buildRoomDetailsFromSelections(roomSelections: RoomSelection[], customRooms: CustomRoom[]) {
  const seededRooms: RoomDetail[] = [];

  roomSelections
    .filter((room) => room.selected && room.quantity > 0)
    .forEach((room) => {
      for (let index = 0; index < room.quantity; index += 1) {
        seededRooms.push({
          id: `room-${room.type}-${index}`,
          name: buildRoomName(room, index),
          type: room.type,
          fixtures: [],
        });
      }
    });

  customRooms.forEach((room) => {
    seededRooms.push({
      id: room.id,
      name: room.name,
      type: room.type,
      fixtures: [],
    });
  });

  return seededRooms;
}

const normalizeRoomKey = (value: string) => value.toLowerCase().trim().replace(/\s+/g, '-');

const normalizeKey = normalizeRoomKey;

function dedupeRoomDetails(rooms: RoomDetail[]) {
  const mergedRooms = new Map<string, RoomDetail>();

  rooms.forEach((room) => {
    const roomKey = `${normalizeRoomKey(room.name)}|${normalizeRoomKey(room.type)}`;
    const existingRoom = mergedRooms.get(roomKey);

    if (!existingRoom) {
      mergedRooms.set(roomKey, {
        ...room,
        fixtures: [...room.fixtures],
      });
      return;
    }

    const existingFixtureKeys = new Set(
      existingRoom.fixtures.map(
        (fixture) => `${normalizeRoomKey(fixture.category)}|${normalizeRoomKey(fixture.name)}|${fixture.quantity}|${fixture.imageUrl || ''}`
      )
    );

    room.fixtures.forEach((fixture) => {
      const fixtureKey = `${normalizeRoomKey(fixture.category)}|${normalizeRoomKey(fixture.name)}|${fixture.quantity}|${fixture.imageUrl || ''}`;
      if (!existingFixtureKeys.has(fixtureKey)) {
        existingFixtureKeys.add(fixtureKey);
        existingRoom.fixtures.push(fixture);
      }
    });
  });

  return Array.from(mergedRooms.values());
}

export default function NewProjectPage() {
  const { user, profile } = useAuth();
  const { showSuccess } = useNotification();
  const { standardRooms } = useSetupDesign();
  const router = useRouter();
  const [currentStep, setCurrentStep] = useState<Step>('basic');
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  // Step 1: Basic Info
  const [projectName, setProjectName] = useState('');
  const [description, setDescription] = useState('');
  const [clientEmail, setClientEmail] = useState('');
  const [budget, setBudget] = useState('');
  const [address, setAddress] = useState('');
  const [clientSearchResults, setClientSearchResults] = useState<any[]>([]);
  const [selectedClient, setSelectedClient] = useState<any>(null);
  const [searchingClient, setSearchingClient] = useState(false);
  const [creatingClient, setCreatingClient] = useState(false);
  const [showCreateClient, setShowCreateClient] = useState(false);
  const [newClientName, setNewClientName] = useState('');
  const [showCredentialsModal, setShowCredentialsModal] = useState(false);
  const [newClientCredentials, setNewClientCredentials] = useState<{
    email: string;
    password: string;
    displayName: string;
  } | null>(null);

  // Step 2: Room Counts (Simple count selector)
  const [roomCounts, setRoomCounts] = useState<RoomCounts>({ 
    bedrooms: 0, 
    bathrooms: 0,
    office: 0,
    diningRoom: 0,
    pantry: 0,
    laundry: 0,
    livingRoom: 0,
    bonusRoom: 0,
  });
  
  // Step 3: Room Names (Auto-generated with edit capability)
  const [generatedRooms, setGeneratedRooms] = useState<GeneratedRoom[]>([]);
  
  // Step 4: Room Selection Options (Fixtures)
  const [roomSelections, setRoomSelections] = useState<RoomSelection[]>(() => buildRoomSelections());
  const [customRooms, setCustomRooms] = useState<CustomRoom[]>([]);
  const [roomDetails, setRoomDetails] = useState<RoomDetail[]>([]);
  const [squareFootage, setSquareFootage] = useState(0);

  // Step 5: Exterior
  const [exteriorDetails, setExteriorDetails] = useState<RoomDetail[]>([
    { id: 'exterior', name: 'Exterior', type: 'exterior', fixtures: [] },
  ]);

  // Step 6: Cabinetry
  const [cabinetrySelections, setCabinetrySelections] = useState<CabinetryDetail[]>([]);

  // Step 7: Categories
  const [categories, setCategories] = useState<CategoryItem[]>(DEFAULT_CATEGORIES);
  const [notesByRoomCategory, setNotesByRoomCategory] = useState<Record<string, string>>({});

  // Step 8: Budgets (Construction Budget Categories)
  const [allowances, setAllowances] = useState<CategoryAllowance[]>([]);
  const [constructionBudget, setConstructionBudget] = useState<{
    categoryCode: string;
    categoryName: string;
    budgetedAmount: number;
  }[]>([]);

  // Step 9: Template
  const [templateName, setTemplateName] = useState('');
  const [saveAsTemplate, setSaveAsTemplate] = useState(false);
  const [selectedTemplateId, setSelectedTemplateId] = useState<string>('empty');
  const templates = (defaultTemplates as any).templates || [];
  const [newCategoryName, setNewCategoryName] = useState('');
  const [scopeOfWorks, setScopeOfWorks] = useState<Record<string, string>>({});

  useEffect(() => {
    void Promise.resolve().then(() => {
      setRoomSelections((current) => {
        const existingByType = new Map(current.map((room) => [room.type, room]));
        return buildRoomSelections(standardRooms).map((room) => ({
          ...room,
          quantity: existingByType.get(room.type)?.quantity || room.quantity,
          selected: existingByType.get(room.type)?.selected || room.selected,
        }));
      });
    });
  }, [standardRooms]);

  // Initialize construction budget with default categories
  useEffect(() => {
    const defaultBudgetCategories = getDefaultBudgetCategories();
    setConstructionBudget(
      defaultBudgetCategories.map((cat) => ({
        categoryCode: cat.code,
        categoryName: cat.name,
        budgetedAmount: 0,
      }))
    );
  }, []);

  const steps: { id: Step; title: string; description: string }[] = [
    { id: 'basic', title: 'Basic Info', description: 'Project name and client' },
    { id: 'budgets', title: 'Construction Budget', description: 'Set budget per construction category' },
    { id: 'roomCounts', title: 'Room Counts', description: 'Bedrooms & bathrooms' },
    { id: 'roomNames', title: 'Room Names', description: 'Review & customize room names' },
    { id: 'roomSelections', title: 'Room Selections', description: 'Choose options by room' },
    { id: 'exterior', title: 'Exterior', description: 'Outdoor selections and counts' },
    { id: 'cabinetry', title: 'Cabinetry', description: 'Cabinetry selections and assignments' },
    { id: 'categories', title: 'Categories', description: 'Required selection categories' },
    { id: 'template', title: 'Save Template', description: 'Optional: Save for reuse' },
  ];

  const currentStepIndex = steps.findIndex(s => s.id === currentStep);

  const searchClients = async (email: string) => {
    if (!email.trim()) {
      setClientSearchResults([]);
      setShowCreateClient(false);
      return;
    }

    try {
      setSearchingClient(true);
      const response = await fetch(`/api/users/search?email=${encodeURIComponent(email)}`);
      const data = await response.json();
      
      if (data.users && data.users.length > 0) {
        setClientSearchResults(data.users);
        setShowCreateClient(false);
      } else {
        // No users found - show create option
        setClientSearchResults([]);
        setShowCreateClient(true);
      }
    } catch (err) {
      console.error('Failed to search clients:', err);
      setClientSearchResults([]);
      setShowCreateClient(false);
    } finally {
      setSearchingClient(false);
    }
  };

  const handleClientSelect = (client: any) => {
    setSelectedClient(client);
    setClientEmail(client.email);
    setClientSearchResults([]);
    setShowCreateClient(false);
  };

  const handleCreateNewClient = async () => {
    if (!clientEmail.trim() || !newClientName.trim()) {
      setError('Email and name are required to create a new client');
      return;
    }

    try {
      setCreatingClient(true);
      setError('');

      // Create the client account
      const response = await fetch('/api/users/create-client', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: clientEmail,
          displayName: newClientName,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to create client');
      }

      // Send welcome email with credentials
      const loginUrl = `${window.location.origin}/login`;
      
      try {
        await fetch('/api/email/welcome', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            to: data.credentials.email,
            displayName: newClientName,
            projectName: projectName || 'Your New Project',
            builderName: profile?.displayName || 'Your Builder',
            email: data.credentials.email,
            password: data.credentials.password,
            loginUrl,
          }),
        });
      } catch (emailError) {
        console.error('Failed to send welcome email:', emailError);
        // Don't fail the whole operation if email fails
      }

      // Select the newly created client
      setSelectedClient(data.user);
      setClientEmail(data.user.email);
      setShowCreateClient(false);
      setNewClientName('');
      
      // Store credentials and show modal
      setNewClientCredentials({
        email: data.credentials.email,
        password: data.credentials.password,
        displayName: newClientName,
      });
      setShowCredentialsModal(true);
    } catch (err) {
      console.error('Failed to create client:', err);
      setError(err instanceof Error ? err.message : 'Failed to create client');
    } finally {
      setCreatingClient(false);
    }
  };

  const handleNext = () => {
    if (currentStepIndex < steps.length - 1) {
      const nextStep = steps[currentStepIndex + 1].id;

      // Convert generated rooms to room details when moving from roomNames to roomSelections
      if (nextStep === 'roomSelections' && generatedRooms.length > 0) {
        const nextRooms: RoomDetail[] = generatedRooms.map(room => ({
          id: room.id,
          name: room.name,
          type: room.type,
          fixtures: [],
        }));
        
        const existingById = new Map(roomDetails.map((room) => [room.id, room]));
        setRoomDetails(
          dedupeRoomDetails(
            nextRooms.map((room) => ({
              ...room,
              fixtures: existingById.get(room.id)?.fixtures || [],
            }))
          )
        );
      }

      // If a template is selected (not empty) and we're moving from basic to roomCounts, apply template
      if (nextStep === 'roomCounts' && selectedTemplateId && selectedTemplateId !== 'empty') {
        const tmpl = templates.find((t: any) => t.id === selectedTemplateId);
        if (tmpl && Array.isArray(tmpl.rooms)) {
          // Count all room types from template
          const bedroomCount = tmpl.rooms.filter((r: any) => r.type === 'bedroom').reduce((sum: number, r: any) => sum + (r.quantity || 0), 0);
          const bathroomCount = tmpl.rooms.filter((r: any) => r.type === 'bathroom').reduce((sum: number, r: any) => sum + (r.quantity || 0), 0);
          const officeCount = tmpl.rooms.filter((r: any) => r.type === 'office').reduce((sum: number, r: any) => sum + (r.quantity || 0), 0);
          const diningRoomCount = tmpl.rooms.filter((r: any) => r.type === 'dining-room' || r.type === 'diningRoom').reduce((sum: number, r: any) => sum + (r.quantity || 0), 0);
          const pantryCount = tmpl.rooms.filter((r: any) => r.type === 'pantry').reduce((sum: number, r: any) => sum + (r.quantity || 0), 0);
          const laundryCount = tmpl.rooms.filter((r: any) => r.type === 'laundry').reduce((sum: number, r: any) => sum + (r.quantity || 0), 0);
          const livingRoomCount = tmpl.rooms.filter((r: any) => r.type === 'living-room' || r.type === 'livingRoom').reduce((sum: number, r: any) => sum + (r.quantity || 0), 0);
          const bonusRoomCount = tmpl.rooms.filter((r: any) => r.type === 'bonus-room' || r.type === 'bonusRoom').reduce((sum: number, r: any) => sum + (r.quantity || 0), 0);
          
          setRoomCounts({ 
            bedrooms: bedroomCount, 
            bathrooms: bathroomCount,
            office: officeCount,
            diningRoom: diningRoomCount,
            pantry: pantryCount,
            laundry: laundryCount,
            livingRoom: livingRoomCount,
            bonusRoom: bonusRoomCount
          });
        }
      }

      setCurrentStep(nextStep);
    }
  };

  const handleBack = () => {
    if (currentStepIndex > 0) {
      setCurrentStep(steps[currentStepIndex - 1].id);
    }
  };

  const handleCategoryToggle = (categoryId: string, required: boolean) => {
    setCategories(prev =>
      prev.map(cat => (cat.id === categoryId ? { ...cat, required } : cat))
    );
  };

  const handleAddCategory = () => {
    const trimmed = newCategoryName.trim();
    if (!trimmed) return;

    if (categories.some(c => c.name.toLowerCase() === trimmed.toLowerCase())) {
      setError('A category with this name already exists');
      return;
    }

    const newCategory: CategoryItem = {
      id: `custom-${Date.now()}`,
      name: trimmed,
      required: true,
      completedCount: 0,
      totalCount: 0,
    };

    setCategories(prev => [...prev, newCategory]);
    setNewCategoryName('');
  };

  const handleAllowanceChange = (categoryId: string, amount: number, type: AllowanceType) => {
    setAllowances(prev => {
      const existing = prev.find(a => a.categoryId === categoryId);
      if (existing) {
        return prev.map(a =>
          a.categoryId === categoryId ? { ...a, amount, type } : a
        );
      }
      return [...prev, { categoryId, amount, type }];
    });
  };

  const handleConstructionBudgetChange = (categoryCode: string, amount: number) => {
    setConstructionBudget(prev =>
      prev.map(item =>
        item.categoryCode === categoryCode
          ? { ...item, budgetedAmount: isNaN(amount) ? 0 : amount }
          : item
      )
    );
  };

  const getTotalConstructionBudget = () => {
    return constructionBudget.reduce((sum, item) => sum + (item.budgetedAmount || 0), 0);
  };

  const handleSubmit = async () => {
    try {
      setSaving(true);
      setError('');

      // Validate required fields
      if (!projectName.trim() || !selectedClient) {
        throw new Error('Project name and client are required');
      }

      const requiredCategories = categories.filter(c => c.required);
      const missingScope = requiredCategories.filter(
        category => !scopeOfWorks[category.id] || scopeOfWorks[category.id].trim().length === 0
      );

      if (missingScope.length > 0) {
        throw new Error('Scope of work is required for all required categories');
      }

      // Build rooms object from the actual room details that will be saved
      const exteriorRoomsToSave = exteriorDetails.filter((room) => room.fixtures.length > 0);
      const allRoomDetails = dedupeRoomDetails([...roomDetails, ...exteriorRoomsToSave]);
      const roomsObject = countRoomsFromDetails(allRoomDetails);

      // Calculate total fixtures
      const totalFixturesCount = allRoomDetails.reduce((sum, room) => sum + room.fixtures.length, 0);

      // Create the project record, then persist the selected room options as subcollections.
      const projectResponseOnly: any = await apiClient.post('/projects', {
        name: projectName,
        builderOrgId: profile?.builderOrgId || user?.uid,
        clientId: selectedClient.uid,
        clientEmail: selectedClient.email,
        status: 'active',
        address: address || '',
        startDate: new Date().toISOString(),
        rooms: roomsObject,
        templateId: selectedTemplateId || null,
        fixtureCounts: {
          plumbingFixtures: totalFixturesCount,
          lightingFixtures: allRoomDetails.reduce((sum, room) => sum + room.fixtures.filter(f => f.category === 'Lighting').length, 0),
        },
        squareFootage: squareFootage || null,
        progress: {
          totalItems: totalFixturesCount,
          completedItems: 0,
          approvedItems: 0,
          pendingItems: totalFixturesCount,
          installedItems: 0,
        },
        createdBy: user?.uid,
      });

      const createdProjectId = projectResponseOnly?.id || projectResponseOnly?.projectId;

      if (!createdProjectId) {
        throw new Error('Failed to create project');
      }

      const createdCategoriesByName = new Map<string, string>();
      const createdRoomIdsByLocalId = new Map<string, string>();
      const createdRoomNamesByLocalId = new Map<string, string>();

      for (const category of categories) {
        const allowance = allowances.find(a => a.categoryId === category.id);
        const response: any = await apiClient.post('/categories', {
          projectId: createdProjectId,
          name: category.name,
          displayOrder: categories.findIndex(c => c.id === category.id),
          required: category.required,
          allowanceType: allowance?.type || 'fixed',
          allowanceAmount: allowance?.amount || 0,
          scopeOfWork: scopeOfWorks[category.id] || null,
        });

        const categoryId = response?.id || response?.categoryId;
        if (categoryId) {
          createdCategoriesByName.set(category.name.toLowerCase(), categoryId);
        }
      }

      for (const room of allRoomDetails) {
        const roomResponse: any = await apiClient.post('/rooms', {
          projectId: createdProjectId,
          name: room.name,
          type: room.type.toLowerCase().replace(' ', '-'),
          fixtureCounts: {
            total: room.fixtures.length,
            assigned: 0,
          },
        });

        const roomId = roomResponse?.id || roomResponse?.roomId;
        if (!roomId) {
          throw new Error(`Failed to create room: ${room.name}`);
        }

        createdRoomIdsByLocalId.set(room.id, roomId);
        createdRoomNamesByLocalId.set(room.id, room.name);

        for (const fixture of room.fixtures) {
          const normalizedCategoryName = fixture.category.toLowerCase();
          let categoryId = createdCategoriesByName.get(normalizedCategoryName);

          if (!categoryId) {
            const categoryResponse: any = await apiClient.post('/categories', {
              projectId: createdProjectId,
              name: fixture.category,
              displayOrder: categories.length + createdCategoriesByName.size,
              required: false,
              allowanceType: 'fixed',
              allowanceAmount: 0,
            });
            categoryId = categoryResponse?.id || categoryResponse?.categoryId;
            if (categoryId) {
              createdCategoriesByName.set(normalizedCategoryName, categoryId);
            }
          }

          await apiClient.post('/items', {
            projectId: createdProjectId,
            categoryId,
            categoryName: fixture.category,
            roomId,
            roomName: room.name,
            name: fixture.name,
            quantity: fixture.quantity,
            imageUrl: fixture.imageUrl || null,
            notes: notesByRoomCategory[`${room.id}-${normalizeRoomKey(fixture.category)}`] || null,
            status: 'notStarted',
            allowance: 0,
            actualCost: 0,
            difference: 0,
            locked: false,
            createdBy: user?.uid,
          });
        }
      }

      const mapPersistedRoomIds = (roomIds: string[] = []) =>
        roomIds.map((roomId) => createdRoomIdsByLocalId.get(roomId) || roomId);

      const mapPersistedRoomNames = (roomIds: string[] = [], roomNames: string[] = []) =>
        roomIds.length > 0
          ? roomIds.map((roomId, index) => createdRoomNamesByLocalId.get(roomId) || roomNames[index] || '')
          : roomNames;

      for (const cabinetry of cabinetrySelections) {
        await apiClient.post('/cabinetry', {
          projectId: createdProjectId,
          cabinetryType: cabinetry.cabinetryType,
          material: cabinetry.material,
          finish: cabinetry.finish,
          doorStyle: cabinetry.doorStyle,
          constructionType: cabinetry.constructionType,
          hardware: cabinetry.hardware,
          notes: cabinetry.notes,
          image: cabinetry.image,
          assignmentType: cabinetry.assignmentType,
          areas: cabinetry.areas || [],
          roomIds: mapPersistedRoomIds(cabinetry.roomIds),
          roomNames: mapPersistedRoomNames(cabinetry.roomIds, cabinetry.roomNames),
          createdBy: user?.uid,
        });
      }

      // Save construction budget
      const totalBudget = getTotalConstructionBudget();
      if (totalBudget > 0) {
        // Create the main budget document
        await apiClient.post('/budget', {
          projectId: createdProjectId,
          totalAmount: totalBudget,
          status: 'draft',
        });

        // Create budget rows for each category with a budget amount
        for (const budgetItem of constructionBudget.filter(item => item.budgetedAmount > 0)) {
          await apiClient.post('/budget/rows', {
            projectId: createdProjectId,
            categoryCode: budgetItem.categoryCode,
            categoryName: budgetItem.categoryName,
            itemCode: `${budgetItem.categoryCode}.000`,
            itemName: budgetItem.categoryName,
            description: `${budgetItem.categoryName} - Initial budget allocation`,
            quantity: 1,
            unitCost: budgetItem.budgetedAmount,
            markup: 0,
            totalAmount: budgetItem.budgetedAmount,
            costType: 'material',
          });
        }
      }

      // Save as template if requested
      if (saveAsTemplate && templateName.trim()) {
        const builderOrgId = profile?.builderOrgId || user?.uid;
        await apiClient.post('/api/templates', {
          name: templateName,
          builderOrgId,
          rooms: roomsObject,
          fixtureCounts: {
            plumbingFixtures: totalFixturesCount,
            lightingFixtures: 0,
          },
          squareFootage: squareFootage || null,
          roomDetails: allRoomDetails,
          categories: requiredCategories.map((c, i) => {
            const allowance = allowances.find(a => a.categoryId === c.id);
            return {
              name: c.name,
              allowanceType: allowance?.type || 'fixed',
              allowanceAmount: allowance?.amount || 0,
              required: true,
            };
          }),
          createdBy: user?.uid,
        });
      }

      showSuccess('Project created successfully');
      router.push(`/projects/${createdProjectId}`);
    } catch (err) {
      console.error('Failed to create project:', err);
      setError(err instanceof Error ? err.message : 'Failed to create project');
    } finally {
      setSaving(false);
    }
  };

  const canProceed = () => {
    switch (currentStep) {
      case 'basic':
        return projectName.trim() && selectedClient && squareFootage > 0;
      case 'roomCounts':
        return roomCounts.bedrooms > 0 || roomCounts.bathrooms > 0;
      case 'roomNames':
        return generatedRooms.length > 0;
      case 'roomSelections':
        return true; // Room selection options are optional
      case 'exterior':
        return true; // Exterior selections are optional
      case 'cabinetry':
        return true; // Cabinetry is optional
      case 'categories':
        if (!categories.some(c => c.required)) return false;
        return categories
          .filter(c => c.required)
          .every(c => scopeOfWorks[c.id] && scopeOfWorks[c.id].trim().length > 0);
      case 'budgets':
        return true;
      case 'template':
        return true;
      default:
        return false;
    }
  };

  if (!user) {
    router.push('/login');
    return null;
  }

  return (
    <div className="min-h-screen bg-taupe-50">
      {/* Header */}
      <nav className="bg-white shadow-sm border-b border-neutral-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex h-16 items-center justify-between">
            <div className="flex min-w-0 items-center gap-4">
              <button
                onClick={() => router.push('/projects')}
                className="text-neutral-600 hover:text-neutral-900"
              >
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
              </button>
              <h1 className="truncate text-xl font-display font-bold text-neutral-900">
                Create New Project
              </h1>
            </div>
          </div>
        </div>
      </nav>

      <main className="max-w-5xl mx-auto py-6 px-4 sm:px-6 sm:py-8 lg:px-8">
        {/* Progress Steps */}
        <div className="mb-8">
          <div className="flex items-start overflow-x-auto pb-3 sm:items-center sm:justify-between">
            {steps.map((step, index) => (
              <div key={step.id} className="flex min-w-[7.5rem] flex-1 items-center">
                <div className="flex flex-1 flex-col items-center">
                  <div
                    className={`w-10 h-10 rounded-full flex items-center justify-center font-semibold transition-all ${
                      index < currentStepIndex
                        ? 'bg-brass-600 text-white'
                        : index === currentStepIndex
                        ? 'bg-brass-600 text-white ring-4 ring-brass-100'
                        : 'bg-neutral-200 text-neutral-600'
                    }`}
                  >
                    {index < currentStepIndex ? (
                      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                      </svg>
                    ) : (
                      index + 1
                    )}
                  </div>
                  <div className="mt-2 text-center">
                    <div className="text-xs font-medium text-neutral-900">{step.title}</div>
                    <div className="text-xs text-neutral-500 hidden sm:block">{step.description}</div>
                  </div>
                </div>
                {index < steps.length - 1 && (
                  <div
                    className={`h-1 min-w-6 flex-1 mx-2 transition-all ${
                      index < currentStepIndex ? 'bg-brass-600' : 'bg-neutral-200'
                    }`}
                  />
                )}
              </div>
            ))}
          </div>
        </div>

        {error && (
          <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-button text-red-700">
            {error}
          </div>
        )}

        {/* Step Content */}
        <Card className="mb-6">
          {/* Step 1: Basic Info */}
          {currentStep === 'basic' && (
            <div className="space-y-6">
              <div>
                <h2 className="text-2xl font-display font-bold text-neutral-900 mb-2">
                  Project Information
                </h2>
                <p className="text-neutral-600">
                  Let's start with the basic details about this project.
                </p>
              </div>

              <Input
                label="Project Name *"
                value={projectName}
                onChange={(e) => setProjectName(e.target.value)}
                placeholder="e.g., Smith Residence"
                required
              />

              <div>
                <label className="block text-sm font-medium text-neutral-700 mb-2">
                  Description
                </label>
                <textarea
                  className="w-full px-4 py-3 border border-neutral-300 rounded-button focus:outline-none focus:ring-2 focus:ring-brass-500 bg-white text-neutral-900"
                  rows={4}
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Brief description of the project"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-neutral-700 mb-2">
                  Address
                </label>
                <Input
                  value={address}
                  onChange={(e) => setAddress(e.target.value)}
                  placeholder="Project address"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-neutral-700 mb-2">
                  Select Client *
                </label>
                <div className="relative">
                  <Input
                    value={clientEmail}
                    onChange={(e) => {
                      setClientEmail(e.target.value);
                      setSelectedClient(null); // Clear selection when typing
                      searchClients(e.target.value);
                    }}
                    placeholder="Search client by email"
                    required
                  />
                  
                  {/* Search Results Dropdown */}
                  {clientSearchResults.length > 0 && (
                    <div className="absolute top-full left-0 right-0 mt-1 bg-white border border-neutral-300 rounded-button shadow-lg z-10 max-h-60 overflow-y-auto">
                      {clientSearchResults.map((client) => (
                        <button
                          key={client.uid}
                          onClick={() => handleClientSelect(client)}
                          className="w-full text-left px-4 py-2 hover:bg-brass-50 border-b border-neutral-200 last:border-b-0"
                        >
                          <div className="font-medium text-neutral-900">{client.displayName || 'Unknown'}</div>
                          <div className="text-sm text-neutral-600">{client.email}</div>
                        </button>
                      ))}
                    </div>
                  )}
                  
                  {/* Searching Indicator */}
                  {searchingClient && (
                    <div className="absolute top-full left-0 right-0 mt-1 bg-white border border-neutral-300 rounded-button shadow-lg z-10 p-3">
                      <div className="text-sm text-neutral-600">Searching...</div>
                    </div>
                  )}
                  
                  {/* Create New Client Option */}
                  {showCreateClient && !searchingClient && clientEmail.trim() && (
                    <div className="absolute top-full left-0 right-0 mt-1 bg-white border border-neutral-300 rounded-button shadow-lg z-10 p-4">
                      <div className="mb-3">
                        <div className="text-sm font-medium text-neutral-900 mb-1">No client found with this email</div>
                        <div className="text-xs text-neutral-600">Create a new client account?</div>
                      </div>
                      
                      <Input
                        value={newClientName}
                        onChange={(e) => setNewClientName(e.target.value)}
                        placeholder="Enter client's full name"
                        className="mb-3"
                      />
                      
                <div className="flex flex-col gap-2 sm:flex-row">
                        <Button
                          onClick={handleCreateNewClient}
                          disabled={creatingClient || !newClientName.trim()}
                          className="flex-1"
                        >
                          {creatingClient ? 'Creating...' : 'Create Client'}
                        </Button>
                        <Button
                          variant="outline"
                          onClick={() => {
                            setShowCreateClient(false);
                            setNewClientName('');
                          }}
                        >
                          Cancel
                        </Button>
                      </div>
                      
                      <div className="mt-3 p-2 bg-brass-50 border border-brass-200 rounded text-xs text-neutral-600">
                        <strong>Note:</strong> A random password will be generated and sent to the client's email.
                      </div>
                    </div>
                  )}
                </div>
                
                {/* Selected Client Display */}
                {selectedClient && (
                  <div className="mt-2 p-3 bg-brass-50 border border-brass-200 rounded-button">
                    <div className="text-sm font-medium text-neutral-900">Selected: {selectedClient.displayName || selectedClient.email}</div>
                  </div>
                )}
              </div>

              <Input
                label="Square Footage"
                type="number"
                min="0"
                value={squareFootage || ''}
                onChange={(e) => setSquareFootage(parseInt(e.target.value) || 0)}
                placeholder="e.g., 2500"
                required
              />

              <Input
                label="Total Budget (optional)"
                type="number"
                value={budget}
                onChange={(e) => setBudget(e.target.value)}
                placeholder="0.00"
              />

              <div>
                <label className="block text-sm font-medium text-neutral-700 mb-2">Project Template</label>
                <select
                  value={selectedTemplateId}
                  onChange={(e) => setSelectedTemplateId(e.target.value)}
                  className="w-full px-4 py-3 border border-neutral-300 rounded-button bg-white"
                >
                  {templates.map((t: any) => (
                    <option key={t.id} value={t.id}>{t.name} - {t.description}</option>
                  ))}
                </select>
                <p className="text-xs text-neutral-500 mt-2">Choose a template to pre-select rooms. You can refine details in the project setup page after creation.</p>
              </div>
            </div>
          )}

          {/* Step 2: Room Counts */}
          {currentStep === 'roomCounts' && (
            <div className="space-y-6">
              <div>
                <h2 className="text-2xl font-display font-bold text-neutral-900 mb-2">
                  Select Room Counts
                </h2>
                <p className="text-neutral-600">
                  How many bedrooms and bathrooms does this project have?
                </p>
              </div>

              <RoomCountSelector
                value={roomCounts}
                onChange={setRoomCounts}
              />
            </div>
          )}

          {/* Step 3: Room Names */}
          {currentStep === 'roomNames' && (
            <div className="space-y-6">
              <div>
                <h2 className="text-2xl font-display font-bold text-neutral-900 mb-2">
                  Name Your Rooms
                </h2>
                <p className="text-neutral-600">
                  We've automatically named your rooms. You can customize any room name by clicking "Edit Name".
                </p>
              </div>

              <AutoGeneratedRoomList
                bedroomCount={roomCounts.bedrooms}
                bathroomCount={roomCounts.bathrooms}
                officeCount={roomCounts.office}
                diningRoomCount={roomCounts.diningRoom}
                pantryCount={roomCounts.pantry}
                laundryCount={roomCounts.laundry}
                livingRoomCount={roomCounts.livingRoom}
                bonusRoomCount={roomCounts.bonusRoom}
                rooms={generatedRooms}
                onChange={setGeneratedRooms}
              />
            </div>
          )}

          {/* Step 4: Room Selections */}
          {currentStep === 'roomSelections' && (
            <div className="space-y-6">
              <div>
                <h2 className="text-2xl font-display font-bold text-neutral-900 mb-2">
                  Room Selection Options
                </h2>
                <p className="text-neutral-600">
                  Choose the selection items needed for each room type. Checked options become client-facing selections when the project is created.
                </p>
              </div>

              <RoomSelectionOptions
                rooms={roomDetails}
                onChange={setRoomDetails}
                notesByRoomCategory={notesByRoomCategory}
                onNotesChange={(roomId, category, notes) =>
                  setNotesByRoomCategory((prev) => ({
                    ...prev,
                    [`${roomId}-${normalizeRoomKey(category)}`]: notes,
                  }))
                }
              />
            </div>
          )}

          {/* Step 5: Exterior */}
          {currentStep === 'exterior' && (
            <div className="space-y-6">
              <div>
                <h2 className="text-2xl font-display font-bold text-neutral-900 mb-2">
                  Exterior Selection Options
                </h2>
                <p className="text-neutral-600">
                  Specify exterior selections such as fans, sconces, pool items, and outdoor living features. Checked options become client-facing selections when the project is created.
                </p>
              </div>

              <RoomSelectionOptions
                rooms={exteriorDetails}
                onChange={setExteriorDetails}
              />
            </div>
          )}

          {/* Step 6: Cabinetry */}
          {currentStep === 'cabinetry' && (
            <div className="space-y-6">
              <div>
                <h2 className="text-2xl font-display font-bold text-neutral-900 mb-2">
                  Cabinetry Selections
                </h2>
                <p className="text-neutral-600">
                  Configure cabinetry selections and assign them to entire home areas or specific rooms. Cabinetry is optional and can be added later.
                </p>
              </div>

              <CabinetryBuilder
                cabinetrySelections={cabinetrySelections}
                onChange={setCabinetrySelections}
                availableRooms={roomDetails.map(r => ({ id: r.id, name: r.name }))}
              />
            </div>
          )}


          {/* Step 7: Categories */}
          {currentStep === 'categories' && (
            <div className="space-y-6">
              <div>
                <h2 className="text-2xl font-display font-bold text-neutral-900 mb-2">
                  Selection Categories
                </h2>
                <p className="text-neutral-600">
                  Choose which categories are required for this project. You can also add custom categories.
                </p>
              </div>

              <CategoryChecklist
                categories={categories}
                onToggleRequired={handleCategoryToggle}
                builderMode={true}
                showProgress={false}
                scopeOfWorks={scopeOfWorks}
                onScopeChange={(id, text) => setScopeOfWorks(prev => ({ ...prev, [id]: text }))}
              />

              {/* Add Custom Category */}
              <Card className="bg-brass-50 border-brass-200">
                <h3 className="text-md font-semibold text-neutral-900 mb-3">
                  Add Custom Category
                </h3>
                <div className="flex flex-col gap-3 sm:flex-row">
                  <Input
                    value={newCategoryName}
                    onChange={(e) => setNewCategoryName(e.target.value)}
                    placeholder="e.g., Window Treatments, Landscaping"
                    className="flex-1"
                  />
                  <Button
                    onClick={handleAddCategory}
                    disabled={!newCategoryName.trim()}
                    variant="outline"
                    className="w-full sm:w-auto"
                  >
                    <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                    </svg>
                    Add Category
                  </Button>
                </div>
              </Card>
            </div>
          )}

          {/* Step 2: Construction Budget */}
          {currentStep === 'budgets' && (
            <div className="space-y-6">
              <div>
                <h2 className="text-2xl font-display font-bold text-neutral-900 mb-2">
                  Construction Budget
                </h2>
                <p className="text-neutral-600">
                  Enter budgeted amounts for each construction category. These will be used for budget tracking, draw requests, and invoices.
                </p>
              </div>

              <div className="space-y-4 max-h-[60vh] overflow-y-auto pr-2">
                {constructionBudget.map((item) => (
                  <div 
                    key={item.categoryCode} 
                    className="flex items-center gap-3 p-4 bg-white border border-neutral-200 rounded-button hover:border-brass-300 transition-colors"
                  >
                    <div className="flex-shrink-0 w-12 h-12 flex items-center justify-center bg-brass-50 rounded-button">
                      <span className="text-sm font-mono font-semibold text-brass-700">
                        {item.categoryCode}
                      </span>
                    </div>
                    <div className="flex-1 min-w-0">
                      <label className="block text-sm font-medium text-neutral-700 mb-1">
                        {item.categoryName}
                      </label>
                      <div className="relative">
                        <span className="absolute left-3 top-1/2 -translate-y-1/2 text-neutral-500">
                          $
                        </span>
                        <input
                          type="number"
                          min="0"
                          step="100"
                          value={item.budgetedAmount || ''}
                          onChange={(e) => handleConstructionBudgetChange(item.categoryCode, parseFloat(e.target.value) || 0)}
                          placeholder="0.00"
                          className="w-full pl-8 pr-4 py-2 border border-neutral-300 rounded-button focus:outline-none focus:ring-2 focus:ring-brass-500 focus:border-transparent"
                        />
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              {/* Total Budget Summary */}
              <div className="mt-6 p-6 bg-gradient-to-br from-brass-50 to-brass-100 border-2 border-brass-300 rounded-button">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="text-sm font-medium text-brass-800 mb-1">
                      Total Project Budget
                    </div>
                    <div className="text-xs text-brass-600">
                      Sum of all construction categories
                    </div>
                  </div>
                  <div className="text-3xl font-bold text-brass-900">
                    ${getTotalConstructionBudget().toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </div>
                </div>
              </div>

              {/* Help Text */}
              <div className="mt-4 p-4 bg-blue-50 border border-blue-200 rounded-button">
                <div className="flex gap-3">
                  <svg className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  <div className="text-sm text-blue-800">
                    <strong>Tip:</strong> You can skip categories you're not sure about and fill them in later. These budgets will be used in the Budget & Draw section for tracking expenses and generating invoices.
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Step 9: Template */}
          {currentStep === 'template' && (
            <div className="space-y-6">
              <div>
                <h2 className="text-2xl font-display font-bold text-neutral-900 mb-2">
                  Save as Template
                </h2>
                <p className="text-neutral-600">
                  Optionally save this configuration as a template to reuse for future projects.
                </p>
              </div>

              <div className="space-y-4">
                <div className="flex items-center gap-3">
                  <input
                    type="checkbox"
                    id="saveTemplate"
                    checked={saveAsTemplate}
                    onChange={(e) => setSaveAsTemplate(e.target.checked)}
                    className="w-5 h-5 text-brass-600 border-neutral-300 rounded focus:ring-brass-500"
                  />
                  <label htmlFor="saveTemplate" className="text-sm font-medium text-neutral-700">
                    Save this configuration as a reusable template
                  </label>
                </div>

                {saveAsTemplate && (
                  <Input
                    type="text"
                    value={templateName}
                    onChange={(e) => setTemplateName(e.target.value)}
                    placeholder="Template name (e.g., Standard 4BR Home)"
                    label="Template Name"
                  />
                )}
              </div>

              {/* Summary */}
              <div className="mt-8 rounded-button bg-taupe-50 p-4 sm:p-6">
                <h3 className="text-lg font-semibold text-neutral-900 mb-4">Project Summary</h3>
                <div className="space-y-2 text-sm">
                  <div className="flex flex-col gap-1 sm:flex-row sm:justify-between">
                    <span className="text-neutral-600">Project Name:</span>
                    <span className="font-medium text-neutral-900">{projectName}</span>
                  </div>
                  <div className="flex flex-col gap-1 sm:flex-row sm:justify-between">
                    <span className="text-neutral-600">Square Footage:</span>
                    <span className="font-medium text-neutral-900">
                      {squareFootage.toLocaleString()} sq ft
                    </span>
                  </div>
                  
                  {/* Room Counts */}
                  <div className="mt-3 pt-3 border-t border-neutral-300">
                    <div className="font-medium text-neutral-900 mb-2">Rooms:</div>
                    {roomSelections.filter(r => r.selected && r.quantity > 0).map(room => (
                      <div key={room.type} className="flex flex-col gap-1 sm:ml-4 sm:flex-row sm:justify-between">
                        <span className="text-neutral-600">{room.displayName}:</span>
                        <span className="font-medium text-neutral-900">{room.quantity}</span>
                      </div>
                    ))}
                    {customRooms.length > 0 && (
                      <div className="flex flex-col gap-1 sm:ml-4 sm:flex-row sm:justify-between">
                        <span className="text-neutral-600">Custom Rooms:</span>
                        <span className="font-medium text-neutral-900">{customRooms.length}</span>
                      </div>
                    )}
                  </div>

                  {/* Fixture Counts by Category */}
                  {[...roomDetails, ...exteriorDetails].some((room) => room.fixtures.length > 0) && (
                    <div className="mt-3 pt-3 border-t border-neutral-300">
                      <div className="font-medium text-neutral-900 mb-2">Fixtures by Category:</div>
                      {(() => {
                        const fixtureCounts: Record<string, number> = {};
                        [...roomDetails, ...exteriorDetails].forEach(room => {
                          room.fixtures.forEach(fixture => {
                            fixtureCounts[fixture.category] = (fixtureCounts[fixture.category] || 0) + fixture.quantity;
                          });
                        });
                        return Object.entries(fixtureCounts).map(([category, count]) => (
                          <div key={category} className="flex flex-col gap-1 sm:ml-4 sm:flex-row sm:justify-between">
                            <span className="text-neutral-600">{category}:</span>
                            <span className="font-medium text-neutral-900">{count}</span>
                          </div>
                        ));
                      })()}
                    </div>
                  )}

                  <div className="mt-3 pt-3 border-t border-neutral-300">
                    <div className="flex flex-col gap-1 sm:flex-row sm:justify-between">
                      <span className="text-neutral-600">Exterior Selections:</span>
                      <span className="font-medium text-neutral-900">
                        {exteriorDetails.reduce((sum, room) => sum + room.fixtures.length, 0)}
                      </span>
                    </div>
                    <div className="flex flex-col gap-1 sm:flex-row sm:justify-between">
                      <span className="text-neutral-600">Cabinetry Selections:</span>
                      <span className="font-medium text-neutral-900">
                        {cabinetrySelections.length}
                      </span>
                    </div>
                    <div className="flex flex-col gap-1 sm:flex-row sm:justify-between">
                      <span className="text-neutral-600">Required Categories:</span>
                      <span className="font-medium text-neutral-900">
                        {categories.filter(c => c.required).length}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}
        </Card>

        {/* Navigation Buttons */}
        <div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-between">
          <Button
            variant="outline"
            onClick={handleBack}
            disabled={currentStepIndex === 0 || saving}
            className="w-full sm:w-auto"
          >
            Back
          </Button>

          {currentStepIndex < steps.length - 1 ? (
            <Button onClick={handleNext} disabled={!canProceed()} className="w-full sm:w-auto">
              Next
            </Button>
          ) : (
            <Button onClick={handleSubmit} disabled={saving || !canProceed()} className="w-full sm:w-auto">
              {saving ? 'Creating Project...' : 'Create Project'}
            </Button>
          )}
        </div>
      </main>

      {/* Credentials Modal */}
      {showCredentialsModal && newClientCredentials && (
        <CredentialsModal
          isOpen={showCredentialsModal}
          onClose={() => setShowCredentialsModal(false)}
          credentials={newClientCredentials}
          projectName={projectName}
        />
      )}
    </div>
  );
}
