'use client';

import { useState, useEffect } from 'react';
import Card from './Card';
import Button from './Button';

export interface GeneratedRoom {
  id: string;
  name: string;
  type: string;
  index: number;
  isEditing?: boolean;
}

interface AutoGeneratedRoomListProps {
  bedroomCount: number;
  bathroomCount: number;
  rooms: GeneratedRoom[];
  onChange: (rooms: GeneratedRoom[]) => void;
}

// Generate smart default room names
function generateDefaultRoomName(type: 'bedroom' | 'bathroom', index: number, total: number): string {
  if (type === 'bedroom') {
    if (index === 0) return 'Primary Bedroom';
    return `Bedroom ${index + 1}`;
  }
  
  if (type === 'bathroom') {
    if (index === 0) return 'Primary Bathroom';
    if (index === total - 1 && total > 1) return 'Half Bath'; // Last bathroom is often a half bath
    return `Bathroom ${index + 1}`;
  }
  
  return '';
}

export default function AutoGeneratedRoomList({
  bedroomCount,
  bathroomCount,
  rooms,
  onChange,
}: AutoGeneratedRoomListProps) {
  const [editingRoomId, setEditingRoomId] = useState<string | null>(null);
  const [editName, setEditName] = useState('');

  // Auto-generate rooms when counts change
  useEffect(() => {
    const generatedRooms: GeneratedRoom[] = [];
    
    // Generate bedrooms
    for (let i = 0; i < bedroomCount; i++) {
      const existingRoom = rooms.find(r => r.type === 'bedroom' && r.index === i);
      generatedRooms.push({
        id: existingRoom?.id || `bedroom-${i}`,
        name: existingRoom?.name || generateDefaultRoomName('bedroom', i, bedroomCount),
        type: 'bedroom',
        index: i,
      });
    }
    
    // Generate bathrooms
    for (let i = 0; i < bathroomCount; i++) {
      const existingRoom = rooms.find(r => r.type === 'bathroom' && r.index === i);
      generatedRooms.push({
        id: existingRoom?.id || `bathroom-${i}`,
        name: existingRoom?.name || generateDefaultRoomName('bathroom', i, bathroomCount),
        type: 'bathroom',
        index: i,
      });
    }
    
    onChange(generatedRooms);
  }, [bedroomCount, bathroomCount]); // Only re-run when counts change

  const handleStartEdit = (room: GeneratedRoom) => {
    setEditingRoomId(room.id);
    setEditName(room.name);
  };

  const handleSaveEdit = (roomId: string) => {
    if (!editName.trim()) return;
    
    const updatedRooms = rooms.map(room => 
      room.id === roomId ? { ...room, name: editName.trim() } : room
    );
    onChange(updatedRooms);
    setEditingRoomId(null);
    setEditName('');
  };

  const handleCancelEdit = () => {
    setEditingRoomId(null);
    setEditName('');
  };

  const bedroomRooms = rooms.filter(r => r.type === 'bedroom');
  const bathroomRooms = rooms.filter(r => r.type === 'bathroom');

  if (rooms.length === 0) {
    return (
      <Card className="p-8 text-center">
        <svg className="w-16 h-16 mx-auto text-neutral-400 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
        </svg>
        <p className="text-neutral-600">
          No rooms to show. Please go back and select the number of bedrooms and bathrooms.
        </p>
      </Card>
    );
  }

  return (
    <div className="space-y-4 sm:space-y-6">
      <div>
        <h3 className="text-base sm:text-lg font-semibold text-neutral-900 mb-2">
          Review & Name Your Rooms
        </h3>
        <p className="text-xs sm:text-sm text-neutral-600">
          We've automatically named your rooms based on common conventions. 
          Click "Edit Name" to customize any room name.
        </p>
      </div>

      {/* Bedrooms */}
      {bedroomRooms.length > 0 && (
        <div>
          <h4 className="text-sm sm:text-md font-semibold text-neutral-800 mb-2 sm:mb-3">
            Bedrooms ({bedroomRooms.length})
          </h4>
          <div className="space-y-2">
            {bedroomRooms.map((room) => (
              <Card key={room.id} className="p-3 sm:p-4">
                <div className="flex items-center justify-between gap-2 sm:gap-4">
                  {editingRoomId === room.id ? (
                    // Edit Mode
                    <>
                      <div className="flex-1 flex items-center gap-2 sm:gap-3 min-w-0">
                        <svg className="w-4 h-4 sm:w-5 sm:h-5 text-brass-600 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
                        </svg>
                        <input
                          type="text"
                          value={editName}
                          onChange={(e) => setEditName(e.target.value)}
                          onKeyDown={(e) => {
                            if (e.key === 'Enter') handleSaveEdit(room.id);
                            if (e.key === 'Escape') handleCancelEdit();
                          }}
                          className="flex-1 min-w-0 px-2 sm:px-3 py-1.5 sm:py-2 text-sm sm:text-base border border-brass-500 rounded-button focus:outline-none focus:ring-2 focus:ring-brass-500"
                          autoFocus
                        />
                      </div>
                      <div className="flex gap-1 sm:gap-2 flex-shrink-0">
                        <Button
                          onClick={() => handleSaveEdit(room.id)}
                          disabled={!editName.trim()}
                          size="sm"
                          className="text-xs sm:text-sm px-2 sm:px-3 py-1 sm:py-1.5"
                        >
                          Save
                        </Button>
                        <Button
                          variant="outline"
                          onClick={handleCancelEdit}
                          size="sm"
                          className="text-xs sm:text-sm px-2 sm:px-3 py-1 sm:py-1.5"
                        >
                          Cancel
                        </Button>
                      </div>
                    </>
                  ) : (
                    // View Mode
                    <>
                      <div className="flex items-center gap-2 sm:gap-3 flex-1 min-w-0">
                        <svg className="w-4 h-4 sm:w-5 sm:h-5 text-brass-600 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
                        </svg>
                        <span className="font-medium text-neutral-900 text-sm sm:text-base truncate">{room.name}</span>
                      </div>
                      <Button
                        variant="ghost"
                        onClick={() => handleStartEdit(room)}
                        size="sm"
                        className="text-xs sm:text-sm px-2 sm:px-3 py-1 sm:py-1.5 flex-shrink-0"
                      >
                        <svg className="w-3 h-3 sm:w-4 sm:h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                        </svg>
                        <span className="hidden sm:inline">Edit Name</span>
                        <span className="sm:hidden">Edit</span>
                      </Button>
                    </>
                  )}
                </div>
              </Card>
            ))}
          </div>
        </div>
      )}

      {/* Bathrooms */}
      {bathroomRooms.length > 0 && (
        <div>
          <h4 className="text-sm sm:text-md font-semibold text-neutral-800 mb-2 sm:mb-3">
            Bathrooms ({bathroomRooms.length})
          </h4>
          <div className="space-y-2">
            {bathroomRooms.map((room) => (
              <Card key={room.id} className="p-3 sm:p-4">
                <div className="flex items-center justify-between gap-2 sm:gap-4">
                  {editingRoomId === room.id ? (
                    // Edit Mode
                    <>
                      <div className="flex-1 flex items-center gap-2 sm:gap-3 min-w-0">
                        <svg className="w-4 h-4 sm:w-5 sm:h-5 text-brass-600 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01" />
                        </svg>
                        <input
                          type="text"
                          value={editName}
                          onChange={(e) => setEditName(e.target.value)}
                          onKeyDown={(e) => {
                            if (e.key === 'Enter') handleSaveEdit(room.id);
                            if (e.key === 'Escape') handleCancelEdit();
                          }}
                          className="flex-1 min-w-0 px-2 sm:px-3 py-1.5 sm:py-2 text-sm sm:text-base border border-brass-500 rounded-button focus:outline-none focus:ring-2 focus:ring-brass-500"
                          autoFocus
                        />
                      </div>
                      <div className="flex gap-1 sm:gap-2 flex-shrink-0">
                        <Button
                          onClick={() => handleSaveEdit(room.id)}
                          disabled={!editName.trim()}
                          size="sm"
                          className="text-xs sm:text-sm px-2 sm:px-3 py-1 sm:py-1.5"
                        >
                          Save
                        </Button>
                        <Button
                          variant="outline"
                          onClick={handleCancelEdit}
                          size="sm"
                          className="text-xs sm:text-sm px-2 sm:px-3 py-1 sm:py-1.5"
                        >
                          Cancel
                        </Button>
                      </div>
                    </>
                  ) : (
                    // View Mode
                    <>
                      <div className="flex items-center gap-2 sm:gap-3 flex-1 min-w-0">
                        <svg className="w-4 h-4 sm:w-5 sm:h-5 text-brass-600 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01" />
                        </svg>
                        <span className="font-medium text-neutral-900 text-sm sm:text-base truncate">{room.name}</span>
                      </div>
                      <Button
                        variant="ghost"
                        onClick={() => handleStartEdit(room)}
                        size="sm"
                        className="text-xs sm:text-sm px-2 sm:px-3 py-1 sm:py-1.5 flex-shrink-0"
                      >
                        <svg className="w-3 h-3 sm:w-4 sm:h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                        </svg>
                        <span className="hidden sm:inline">Edit Name</span>
                        <span className="sm:hidden">Edit</span>
                      </Button>
                    </>
                  )}
                </div>
              </Card>
            ))}
          </div>
        </div>
      )}

      {/* Summary */}
      <Card className="p-4 bg-brass-50 border-brass-200">
        <div className="flex items-start gap-3">
          <svg className="w-5 h-5 text-brass-600 mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <div className="flex-1">
            <p className="text-sm font-medium text-neutral-900 mb-1">
              Room Configuration Complete
            </p>
            <p className="text-sm text-neutral-600">
              {bedroomRooms.length} {bedroomRooms.length === 1 ? 'bedroom' : 'bedrooms'} and{' '}
              {bathroomRooms.length} {bathroomRooms.length === 1 ? 'bathroom' : 'bathrooms'} configured.
              You can customize names now or continue to add fixtures for each room on the next step.
            </p>
          </div>
        </div>
      </Card>
    </div>
  );
}
