'use client';

import { useState, useEffect } from 'react';
import Card from './Card';
import Button from './Button';

export interface GeneratedRoom {
  id: string;
  name: string;
  type: string;
  index: number;
  isEditing?: boolean;
}

interface AutoGeneratedRoomListProps {
  bedroomCount: number;
  bathroomCount: number;
  officeCount: number;
  diningRoomCount: number;
  pantryCount: number;
  laundryCount: number;
  livingRoomCount: number;
  bonusRoomCount: number;
  rooms: GeneratedRoom[];
  onChange: (rooms: GeneratedRoom[]) => void;
}

type RoomType = 'bedroom' | 'bathroom' | 'office' | 'diningRoom' | 'pantry' | 'laundry' | 'livingRoom' | 'bonusRoom';

// Generate smart default room names
function generateDefaultRoomName(type: RoomType, index: number, total: number): string {
  switch (type) {
    case 'bedroom':
      if (index === 0) return 'Primary Bedroom';
      return `Bedroom ${index + 1}`;
    case 'bathroom':
      if (index === 0) return 'Primary Bathroom';
      if (index === total - 1 && total > 1) return 'Half Bath';
      return `Bathroom ${index + 1}`;
    case 'office':
      return total === 1 ? 'Office' : `Office ${index + 1}`;
    case 'diningRoom':
      return total === 1 ? 'Dining Room' : `Dining Room ${index + 1}`;
    case 'pantry':
      return total === 1 ? 'Pantry' : `Pantry ${index + 1}`;
    case 'laundry':
      return total === 1 ? 'Laundry Room' : `Laundry Room ${index + 1}`;
    case 'livingRoom':
      return total === 1 ? 'Living Room' : `Living Room ${index + 1}`;
    case 'bonusRoom':
      return total === 1 ? 'Bonus Room' : `Bonus Room ${index + 1}`;
    default:
      return '';
  }
}

export default function AutoGeneratedRoomList({
  bedroomCount,
  bathroomCount,
  officeCount,
  diningRoomCount,
  pantryCount,
  laundryCount,
  livingRoomCount,
  bonusRoomCount,
  rooms,
  onChange,
}: AutoGeneratedRoomListProps) {
  const [editingRoomId, setEditingRoomId] = useState<string | null>(null);
  const [editName, setEditName] = useState('');

  // Auto-generate rooms when counts change
  useEffect(() => {
    const generatedRooms: GeneratedRoom[] = [];
    
    // Helper function to generate rooms for a type
    const generateRoomsForType = (type: RoomType, count: number) => {
      for (let i = 0; i < count; i++) {
        const existingRoom = rooms.find(r => r.type === type && r.index === i);
        generatedRooms.push({
          id: existingRoom?.id || `${type}-${i}`,
          name: existingRoom?.name || generateDefaultRoomName(type, i, count),
          type,
          index: i,
        });
      }
    };
    
    // Generate all room types
    generateRoomsForType('bedroom', bedroomCount);
    generateRoomsForType('bathroom', bathroomCount);
    generateRoomsForType('office', officeCount);
    generateRoomsForType('diningRoom', diningRoomCount);
    generateRoomsForType('pantry', pantryCount);
    generateRoomsForType('laundry', laundryCount);
    generateRoomsForType('livingRoom', livingRoomCount);
    generateRoomsForType('bonusRoom', bonusRoomCount);
    
    onChange(generatedRooms);
  }, [bedroomCount, bathroomCount, officeCount, diningRoomCount, pantryCount, laundryCount, livingRoomCount, bonusRoomCount]); // Only re-run when counts change

  const handleStartEdit = (room: GeneratedRoom) => {
    setEditingRoomId(room.id);
    setEditName(room.name);
  };

  const handleSaveEdit = (roomId: string) => {
    if (!editName.trim()) return;
    
    const updatedRooms = rooms.map(room => 
      room.id === roomId ? { ...room, name: editName.trim() } : room
    );
    onChange(updatedRooms);
    setEditingRoomId(null);
    setEditName('');
  };

  const handleCancelEdit = () => {
    setEditingRoomId(null);
    setEditName('');
  };

  const bedroomRooms = rooms.filter(r => r.type === 'bedroom');
  const bathroomRooms = rooms.filter(r => r.type === 'bathroom');
  const officeRooms = rooms.filter(r => r.type === 'office');
  const diningRoomRooms = rooms.filter(r => r.type === 'diningRoom');
  const pantryRooms = rooms.filter(r => r.type === 'pantry');
  const laundryRooms = rooms.filter(r => r.type === 'laundry');
  const livingRoomRooms = rooms.filter(r => r.type === 'livingRoom');
  const bonusRoomRooms = rooms.filter(r => r.type === 'bonusRoom');

  // Helper to render a room group
  const renderRoomGroup = (groupRooms: GeneratedRoom[], title: string, icon: string) => {
    if (groupRooms.length === 0) return null;

    return (
      <div>
        <h4 className="text-sm sm:text-md font-semibold text-neutral-800 mb-2 sm:mb-3 flex items-center gap-2">
          <span>{icon}</span>
          <span>{title} ({groupRooms.length})</span>
        </h4>
        <div className="space-y-2">
          {groupRooms.map((room) => (
            <Card key={room.id} className="p-3 sm:p-4">
              <div className="flex items-center justify-between gap-2 sm:gap-4">
                {editingRoomId === room.id ? (
                  // Edit Mode
                  <>
                    <div className="flex-1 flex items-center gap-2 sm:gap-3 min-w-0">
                      <span className="text-xl flex-shrink-0">{icon}</span>
                      <input
                        type="text"
                        value={editName}
                        onChange={(e) => setEditName(e.target.value)}
                        onKeyDown={(e) => {
                          if (e.key === 'Enter') handleSaveEdit(room.id);
                          if (e.key === 'Escape') handleCancelEdit();
                        }}
                        className="flex-1 min-w-0 px-2 sm:px-3 py-1.5 sm:py-2 text-sm sm:text-base border border-brass-500 rounded-button focus:outline-none focus:ring-2 focus:ring-brass-500"
                        autoFocus
                      />
                    </div>
                    <div className="flex gap-1 sm:gap-2 flex-shrink-0">
                      <Button
                        onClick={() => handleSaveEdit(room.id)}
                        disabled={!editName.trim()}
                        size="sm"
                        className="text-xs sm:text-sm px-2 sm:px-3 py-1 sm:py-1.5"
                      >
                        Save
                      </Button>
                      <Button
                        variant="outline"
                        onClick={handleCancelEdit}
                        size="sm"
                        className="text-xs sm:text-sm px-2 sm:px-3 py-1 sm:py-1.5"
                      >
                        Cancel
                      </Button>
                    </div>
                  </>
                ) : (
                  // View Mode
                  <>
                    <div className="flex items-center gap-2 sm:gap-3 flex-1 min-w-0">
                      <span className="text-xl flex-shrink-0">{icon}</span>
                      <span className="font-medium text-neutral-900 text-sm sm:text-base truncate">{room.name}</span>
                    </div>
                    <Button
                      variant="ghost"
                      onClick={() => handleStartEdit(room)}
                      size="sm"
                      className="text-xs sm:text-sm px-2 sm:px-3 py-1 sm:py-1.5 flex-shrink-0"
                    >
                      <svg className="w-3 h-3 sm:w-4 sm:h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                      </svg>
                      <span className="hidden sm:inline">Edit Name</span>
                      <span className="sm:hidden">Edit</span>
                    </Button>
                  </>
                )}
              </div>
            </Card>
          ))}
        </div>
      </div>
    );
  };

  if (rooms.length === 0) {
    return (
      <Card className="p-8 text-center">
        <svg className="w-16 h-16 mx-auto text-neutral-400 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
        </svg>
        <p className="text-neutral-600">
          No rooms to show. Please go back and select the number of bedrooms and bathrooms.
        </p>
      </Card>
    );
  }

  const totalRooms = rooms.length;
  
  return (
    <div className="space-y-4 sm:space-y-6">
      <div>
        <h3 className="text-base sm:text-lg font-semibold text-neutral-900 mb-2">
          Review & Name Your Rooms
        </h3>
        <p className="text-xs sm:text-sm text-neutral-600">
          We've automatically named your rooms based on common conventions. 
          Click "Edit Name" to customize any room name.
        </p>
      </div>

      {/* Render all room types using helper function */}
      {renderRoomGroup(bedroomRooms, 'Bedrooms', '🛏️')}
      {renderRoomGroup(bathroomRooms, 'Bathrooms', '🚿')}
      {renderRoomGroup(officeRooms, 'Offices', '💼')}
      {renderRoomGroup(diningRoomRooms, 'Dining Rooms', '🍽️')}
      {renderRoomGroup(pantryRooms, 'Pantries', '🥫')}
      {renderRoomGroup(laundryRooms, 'Laundry Rooms', '🧺')}
      {renderRoomGroup(livingRoomRooms, 'Living Rooms', '🛋️')}
      {renderRoomGroup(bonusRoomRooms, 'Bonus Rooms', '✨')}

      {/* Summary */}
      <Card className="p-4 bg-brass-50 border-brass-200">
        <div className="flex items-start gap-3">
          <svg className="w-5 h-5 text-brass-600 mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <div className="flex-1">
            <p className="text-sm font-medium text-neutral-900 mb-1">
              Room Configuration Complete
            </p>
            <p className="text-sm text-neutral-600">
              {totalRooms} {totalRooms === 1 ? 'room' : 'rooms'} configured
              {bedroomRooms.length > 0 && ` (${bedroomRooms.length} ${bedroomRooms.length === 1 ? 'bedroom' : 'bedrooms'})`}
              {bathroomRooms.length > 0 && `, ${bathroomRooms.length} ${bathroomRooms.length === 1 ? 'bathroom' : 'bathrooms'}`}
              {officeRooms.length > 0 && `, ${officeRooms.length} ${officeRooms.length === 1 ? 'office' : 'offices'}`}
              {diningRoomRooms.length > 0 && `, ${diningRoomRooms.length} ${diningRoomRooms.length === 1 ? 'dining room' : 'dining rooms'}`}
              {pantryRooms.length > 0 && `, ${pantryRooms.length} ${pantryRooms.length === 1 ? 'pantry' : 'pantries'}`}
              {laundryRooms.length > 0 && `, ${laundryRooms.length} ${laundryRooms.length === 1 ? 'laundry room' : 'laundry rooms'}`}
              {livingRoomRooms.length > 0 && `, ${livingRoomRooms.length} ${livingRoomRooms.length === 1 ? 'living room' : 'living rooms'}`}
              {bonusRoomRooms.length > 0 && `, ${bonusRoomRooms.length} ${bonusRoomRooms.length === 1 ? 'bonus room' : 'bonus rooms'}`}.
              You can customize names now or continue to add fixtures for each room on the next step.
            </p>
          </div>
        </div>
      </Card>
    </div>
  );
}
